### ISSUE TITLE
Implementation: Elixir

### ISSUE THREAD

**Issue by KieranP** [KieranP/Game-Of-Life-Implementations#15]
https://elixir-lang.org/

**Comment by ihaveint** [comment]
Hi there, 
I would like to implement an elixir version.
Since in the README it's mentioned that the goal is `to create near identical implementations of "Conway's Game of Life" (GOL) in multiple programming languages`, I need to take a look at the codebase and see if I can do that. 
I'll let you know :)

**Comment by KieranP** [comment]
Closed in a4360f15ff3c645c58f8d3a7342e35667899b621
